# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#LOCAL BUILDING: bundle exec jekyll serve

show_excerpts: true
title: Jackson's Digital Portfolio
email: jackson.marshall1204@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Jackson Marshall's personal website showcasing projects, interests, and more!
#baseurl: "/Personal-Website-V2" #domain name has been added, no need for basename
url: "https://jax-y1.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  GitHub
github_link: https://github.com/JaX-Y1
linkedin_username: LinkedIn
linkedin_link: https://www.linkedin.com/in/andrewjmarshall2
instragram_username: Instagram
instagram_link: https://www.instagram.com/applejacks3055/
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "_posts"
      type: "posts"
    values:
      permalink: "blog/:title:output_ext"



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
